version: "3.8"
services:
  db:
    image: postgres:15                # Use official Postgres 15 image
    restart: unless-stopped           # Automatically restart unless manually stopped
    environment:
      POSTGRES_USER: postgres        # Postgres username
      POSTGRES_PASSWORD: postgres    # Postgres password
      POSTGRES_DB: app_db            # Database name
    ports:
      - "5431:5432"                  # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data across container restarts

volumes:
  postgres_data:                      # Named volume for Postgres persistent storage
